### ISSUE TITLE
Backend worker process died

### ISSUE THREAD

**Issue by KosarKeshavarz** [HaoLiuHust/GroundingDINO-Service#2]
after creating .mar file and moving the file  to the model_store, i tried running  it using the command provided. i checked the log file using:
sudo docker logs -f groundingdino 
i came across a warning  saying  warnings.warn("Failed to load custom C++ ops. Running on CPU mode Only!") (i attached the log file  [
[log.txt](https://github.com/HaoLiuHust/GroundingDINO-Service/files/12387947/log.txt)
) 

i would be grateful if you guide me through this . i installed nvidia-container-toolkit and i ran docker using nvidia runtime.
(sorry for the wrong issue tittle)

**Comment by HaoLiuHust** [comment]
```
2023-08-20T07:37:13,174 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG - final text_encoder_type: /tmp/models/6d453caac8b04724bca89f54d38f3503
2023-08-20T07:37:13,174 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG - Backend worker process died.
2023-08-20T07:37:13,174 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG - Traceback (most recent call last):
2023-08-20T07:37:13,174 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -   File "/opt/conda/lib/python3.10/site-packages/ts/model_service_worker.py", line 253, in <module>
2023-08-20T07:37:13,174 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -     worker.run_server()
2023-08-20T07:37:13,175 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -   File "/opt/conda/lib/python3.10/site-packages/ts/model_service_worker.py", line 221, in run_server
2023-08-20T07:37:13,175 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -     self.handle_connection(cl_socket)
2023-08-20T07:37:13,175 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -   File "/opt/conda/lib/python3.10/site-packages/ts/model_service_worker.py", line 184, in handle_connection
2023-08-20T07:37:13,175 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -     service, result, code = self.load_model(msg)
2023-08-20T07:37:13,175 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -   File "/opt/conda/lib/python3.10/site-packages/ts/model_service_worker.py", line 131, in load_model
2023-08-20T07:37:13,175 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -     service = model_loader.load(
2023-08-20T07:37:13,175 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -   File "/opt/conda/lib/python3.10/site-packages/ts/model_loader.py", line 135, in load
2023-08-20T07:37:13,176 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -     initialize_fn(service.context)
2023-08-20T07:37:13,176 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -   File "/tmp/models/6d453caac8b04724bca89f54d38f3503/grounding_dino_handler.py", line 60, in initialize
2023-08-20T07:37:13,176 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -     self.model = build_model(args)
2023-08-20T07:37:13,176 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -   File "/workspace/src/groundingdino/groundingdino/models/__init__.py", line 17, in build_model
2023-08-20T07:37:13,176 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -     model = build_func(args)
2023-08-20T07:37:13,177 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -   File "/workspace/src/groundingdino/groundingdino/models/GroundingDINO/groundingdino.py", line 388, in build_groundingdino
2023-08-20T07:37:13,177 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -     model = GroundingDINO(
2023-08-20T07:37:13,177 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -   File "/workspace/src/groundingdino/groundingdino/models/GroundingDINO/groundingdino.py", line 107, in __init__
2023-08-20T07:37:13,177 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -     self.tokenizer = get_tokenlizer.get_tokenlizer(text_encoder_type)
2023-08-20T07:37:13,177 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -   File "/workspace/src/groundingdino/groundingdino/util/get_tokenlizer.py", line 19, in get_tokenlizer
2023-08-20T07:37:13,178 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -     tokenizer = AutoTokenizer.from_pretrained(text_encoder_type)
2023-08-20T07:37:13,178 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -   File "/opt/conda/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 652, in from_pretrained
2023-08-20T07:37:13,178 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -     tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
2023-08-20T07:37:13,178 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -   File "/opt/conda/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 517, in get_tokenizer_config
2023-08-20T07:37:13,178 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -     result = json.load(reader)
2023-08-20T07:37:13,178 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -   File "/opt/conda/lib/python3.10/json/__init__.py", line 293, in load
2023-08-20T07:37:13,178 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -     return loads(fp.read(),
2023-08-20T07:37:13,178 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -   File "/opt/conda/lib/python3.10/json/__init__.py", line 346, in loads
2023-08-20T07:37:13,179 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -     return _default_decoder.decode(s)
2023-08-20T07:37:13,179 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -   File "/opt/conda/lib/python3.10/json/decoder.py", line 337, in decode
2023-08-20T07:37:13,179 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2023-08-20T07:37:13,179 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -   File "/opt/conda/lib/python3.10/json/decoder.py", line 355, in raw_decode
2023-08-20T07:37:13,179 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -     raise JSONDecodeError("Expecting value", s, err.value) from None
```

seems lack of some transformer json config

**Comment by KosarKeshavarz** [comment]
> ```
> 2023-08-20T07:37:13,174 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG - final text_encoder_type: /tmp/models/6d453caac8b04724bca89f54d38f3503
> 2023-08-20T07:37:13,174 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG - Backend worker process died.
> 2023-08-20T07:37:13,174 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG - Traceback (most recent call last):
> 2023-08-20T07:37:13,174 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -   File "/opt/conda/lib/python3.10/site-packages/ts/model_service_worker.py", line 253, in <module>
> 2023-08-20T07:37:13,174 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -     worker.run_server()
> 2023-08-20T07:37:13,175 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -   File "/opt/conda/lib/python3.10/site-packages/ts/model_service_worker.py", line 221, in run_server
> 2023-08-20T07:37:13,175 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -     self.handle_connection(cl_socket)
> 2023-08-20T07:37:13,175 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -   File "/opt/conda/lib/python3.10/site-packages/ts/model_service_worker.py", line 184, in handle_connection
> 2023-08-20T07:37:13,175 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -     service, result, code = self.load_model(msg)
> 2023-08-20T07:37:13,175 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -   File "/opt/conda/lib/python3.10/site-packages/ts/model_service_worker.py", line 131, in load_model
> 2023-08-20T07:37:13,175 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -     service = model_loader.load(
> 2023-08-20T07:37:13,175 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -   File "/opt/conda/lib/python3.10/site-packages/ts/model_loader.py", line 135, in load
> 2023-08-20T07:37:13,176 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -     initialize_fn(service.context)
> 2023-08-20T07:37:13,176 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -   File "/tmp/models/6d453caac8b04724bca89f54d38f3503/grounding_dino_handler.py", line 60, in initialize
> 2023-08-20T07:37:13,176 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -     self.model = build_model(args)
> 2023-08-20T07:37:13,176 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -   File "/workspace/src/groundingdino/groundingdino/models/__init__.py", line 17, in build_model
> 2023-08-20T07:37:13,176 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -     model = build_func(args)
> 2023-08-20T07:37:13,177 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -   File "/workspace/src/groundingdino/groundingdino/models/GroundingDINO/groundingdino.py", line 388, in build_groundingdino
> 2023-08-20T07:37:13,177 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -     model = GroundingDINO(
> 2023-08-20T07:37:13,177 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -   File "/workspace/src/groundingdino/groundingdino/models/GroundingDINO/groundingdino.py", line 107, in __init__
> 2023-08-20T07:37:13,177 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -     self.tokenizer = get_tokenlizer.get_tokenlizer(text_encoder_type)
> 2023-08-20T07:37:13,177 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -   File "/workspace/src/groundingdino/groundingdino/util/get_tokenlizer.py", line 19, in get_tokenlizer
> 2023-08-20T07:37:13,178 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -     tokenizer = AutoTokenizer.from_pretrained(text_encoder_type)
> 2023-08-20T07:37:13,178 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -   File "/opt/conda/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 652, in from_pretrained
> 2023-08-20T07:37:13,178 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -     tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
> 2023-08-20T07:37:13,178 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -   File "/opt/conda/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 517, in get_tokenizer_config
> 2023-08-20T07:37:13,178 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -     result = json.load(reader)
> 2023-08-20T07:37:13,178 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -   File "/opt/conda/lib/python3.10/json/__init__.py", line 293, in load
> 2023-08-20T07:37:13,178 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -     return loads(fp.read(),
> 2023-08-20T07:37:13,178 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -   File "/opt/conda/lib/python3.10/json/__init__.py", line 346, in loads
> 2023-08-20T07:37:13,179 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -     return _default_decoder.decode(s)
> 2023-08-20T07:37:13,179 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -   File "/opt/conda/lib/python3.10/json/decoder.py", line 337, in decode
> 2023-08-20T07:37:13,179 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
> 2023-08-20T07:37:13,179 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -   File "/opt/conda/lib/python3.10/json/decoder.py", line 355, in raw_decode
> 2023-08-20T07:37:13,179 [INFO ] W-9000-groundingdino_1.0-stdout MODEL_LOG -     raise JSONDecodeError("Expecting value", s, err.value) from None
> ```
> 
> seems lack of some transformer json config

yes there was a missing file . but the serious problem i have is the warning :
/workspace/src/groundingdino/groundingdino/models/GroundingDINO/ms_deform_attn.py:31: UserWarning: Failed to load custom C++ ops. Running on CPU mode Only!

I checked the setup.py and it seems it loads some extensions including  _C extension : 
https://github.com/IDEA-Research/GroundingDINO/blob/60d796825e1266e56f7e4e9e00e88de662b67bd3/setup.py#L206

in ms_deform_attn.py, it uses this extension module but is not able to find it! 

I even checked CUDA_HOME to be set using the command below:
udo docker run -d --runtime=nvidia --gpus all -e CUDA_HOME='/usr/local/cuda' --name groundingdino -v $(pwd)/model_store:/model_store -p 8080:8080 -p 8081:8081 -p 8082:8082 torchserve:groundingdino bash -c "torchserve --start --foreground --model-store /model_store --models groundingdino=groundingdino.mar"

but nothing worked!

**Comment by HaoLiuHust** [comment]
have you installed groundingdino in docker or just cloned groundingdino project?

**Comment by KosarKeshavarz** [comment]
> have you installed groundingdino in docker or just cloned groundingdino project?

I followed the instructions strictly, you have mentioned the installation of grounding dino in requirments.txt. so yes it is installed.
I've noticed so many people have come across this problem in the original grounding dino project issues. some solved it using setting CUDA_HOME environment variable and some people tried other solutions. ( [https://github.com/IDEA-Research/GroundingDINO/issues/8](url) ).   nothing woked for my case yet

**Comment by HaoLiuHust** [comment]
sorry, I have not encountered this problem, can't give you more help
